### ISSUE TITLE
Globally changes Data::Dumper behaviour

### ISSUE THREAD

**Issue by tehmoth** [wimvanderbauwhede/Perl-Parser-Combinators#3]
In Parser/Combinators.pm
$Data::Dumper::Indent=0;
$Data::Dumper::Terse =1;
changes the default output format of Data::Dumper::Dumper after that.

Perhaps localize them in functions that use them

**Comment by wimvanderbauwhede** [comment]
Thanks, that was sloppy of me. Fixed it in 0.05.
